# Generated by Django 4.0.4 on 2023-08-24 03:50

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_appointment_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='death_certificate',
            field=models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='death_certificates/', validators=[app.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='husband_birth_certificate',
            field=models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='birth_certificates/', validators=[app.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='wife_birth_certificate',
            field=models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='birth_certificates/', validators=[app.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='archivedfile',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.appointment'),
        ),
        migrations.AlterUniqueTogether(
            name='archivedfile',
            unique_together={('appointment', 'archived_file')},
        ),
    ]
