# Generated by Django 4.2.7 on 2023-12-03 21:14

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_checkouthistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkouthistory',
            name='order',
        ),
        migrations.RemoveField(
            model_name='checkouthistory',
            name='user',
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='order_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
    ]
