# Generated by Django 4.0.4 on 2023-03-13 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='owner',
            new_name='user',
        ),
        migrations.AddField(
            model_name='appointment',
            name='husband_birth_certificate',
            field=models.FileField(blank=True, upload_to='birth_certificates'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name_of_first_witness',
            field=models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name_of_husband',
            field=models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=69, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name_of_officer',
            field=models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name_of_second_witness',
            field=models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='name_of_wife',
            field=models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='number_of_attendees',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='appointment',
            name='wife_birth_certificate',
            field=models.FileField(blank=True, upload_to='birth_certificates'),
        ),
    ]
