# Generated by Django 4.0.4 on 2023-03-13 11:31

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_appointment_address_appointment_fathers_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='age',
            field=models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='appointment',
            name='date_of_death',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deacons',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Deacon(s)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='death_certificate',
            field=models.FileField(blank=True, upload_to='death_certificates'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='deceased_full_name',
            field=models.CharField(blank=True, default='', help_text='Surname FirstName, MiddleName', max_length=50, null=True, verbose_name="Father's Full Name"),
        ),
        migrations.AddField(
            model_name='appointment',
            name='entrance_hymn',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='first_reading',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='gift_bearers_for_the_offering',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='lectors_or_readers',
            field=models.CharField(blank=True, default='', max_length=50, null=True, verbose_name='Lector(s) or Reader(s)'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='musical_reading',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='opening_collect',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='place_of_burial_cemetery',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='placement_of_the_pall',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='prelude_music',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='responsorial_psalm',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='second_reading',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='text_of_response',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
