# Generated by Django 4.0.4 on 2023-08-22 13:36

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_appointment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='deacons',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='lectors_or_readers',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='musical_reading',
        ),
        migrations.AddField(
            model_name='appointment',
            name='status_description',
            field=models.TextField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='death_certificate',
            field=models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='death_certificates', validators=[app.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='husband_birth_certificate',
            field=models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='birth_certificates', validators=[app.models.validate_file_extension]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='purpose',
            field=models.IntegerField(choices=[(1, 'Wedding'), (2, 'Baptism'), (3, 'Funeral')], default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Confirmed'), (3, 'Done'), (4, 'Rejected')], default=1),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='wife_birth_certificate',
            field=models.FileField(blank=True, help_text='Submit the file: pdf, doc, docx', upload_to='birth_certificates', validators=[app.models.validate_file_extension]),
        ),
    ]
