# Generated by Django 4.0.4 on 2023-08-24 03:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_appointment_deacons_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status_description',
            field=models.TextField(blank=True, default='Your appointment is not yet approved, just wait a few hours before getting approved, thank you.', help_text='Describe the reason for changing the status', max_length=255),
        ),
        migrations.CreateModel(
            name='ArchivedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_file', models.FileField(upload_to='archived_files/')),
                ('archived_date', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.appointment')),
            ],
        ),
    ]
