# Generated by Django 4.0.4 on 2023-10-17 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_appointment_officiant'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('discount', models.FloatField()),
                ('quantity', models.SmallIntegerField()),
                ('createdat', models.DateTimeField(db_column='createdAt')),
                ('updatedat', models.DateTimeField(blank=True, db_column='updatedAt', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(max_length=75)),
                ('price', models.FloatField()),
                ('thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='services/')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, default='', null=True, upload_to='services/')),
            ],
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='address',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='age',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='archived',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='date_of_death',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='death_certificate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='deceased_full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='entrance_hymn',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='fathers_full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='first_reading',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='gift_bearers_for_the_offering',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='godparents',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='husband_birth_certificate',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='mothers_full_name',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_of_first_witness',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_of_husband',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_of_officer',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_of_second_witness',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='name_of_wife',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='number_of_attendees',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='opening_collect',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='place_of_burial_cemetery',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='placement_of_the_pall',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='prelude_music',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='purpose',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='responsorial_psalm',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='second_reading',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='status_description',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='text_of_response',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='user',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='wife_birth_certificate',
        ),
        migrations.AddField(
            model_name='appointment',
            name='action_message',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
        migrations.AddField(
            model_name='appointment',
            name='action_taken',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Pending'), (1, 'Accept'), (2, 'Delete'), (3, 'Decline')], default=1),
        ),
        migrations.AddField(
            model_name='appointment',
            name='customer',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='payment_method',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Fully Paid'), (2, 'Balance'), (3, 'Promisory Note')], default=2),
        ),
        migrations.AddField(
            model_name='customuser',
            name='gender',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Male'), (1, 'Female'), (2, 'Other')], default=0),
        ),
        migrations.DeleteModel(
            name='ArchivedFile',
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.service'),
        ),
    ]
