# Generated by Django 4.0.4 on 2023-10-17 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_alter_product_name_alter_service_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='action_taken',
            new_name='status',
        ),
    ]
