# Generated by Django 4.0.4 on 2023-10-18 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_service_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='createdat',
        ),
        migrations.RemoveField(
            model_name='order',
            name='updatedat',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
