# Generated by Django 4.0.4 on 2023-10-18 07:35

import app.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='phone_number',
            field=app.custom_fields.PhoneNumberField(default='', max_length=15),
        ),
    ]
