# Generated by Django 4.0.4 on 2023-10-18 09:23

import app.custom_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_customuser_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='phone_number',
            field=app.custom_fields.PhoneNumberField(blank=True, default='', max_length=15),
        ),
    ]
