# Generated by Django 4.2.7 on 2023-12-03 21:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_remove_checkouthistory_order_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='checkouthistory',
            old_name='price',
            new_name='total_price',
        ),
        migrations.RemoveField(
            model_name='checkouthistory',
            name='date',
        ),
        migrations.RemoveField(
            model_name='checkouthistory',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='checkouthistory',
            name='product',
        ),
        migrations.RemoveField(
            model_name='checkouthistory',
            name='quantity',
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='date_of_checkout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='total_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkouthistory',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
